namespace Ddap.Core;

/// <summary>
/// Represents the configuration for a property/column of an entity.
/// </summary>
public interface IPropertyConfiguration
{
    /// <summary>
    /// Gets the name of the property.
    /// </summary>
    string PropertyName { get; }

    /// <summary>
    /// Gets the database column name.
    /// </summary>
    string ColumnName { get; }

    /// <summary>
    /// Gets the CLR type of the property.
    /// </summary>
    Type PropertyType { get; }

    /// <summary>
    /// Gets the database type name.
    /// </summary>
    string DatabaseType { get; }

    /// <summary>
    /// Gets a value indicating whether this property is part of the primary key.
    /// </summary>
    bool IsPrimaryKey { get; }

    /// <summary>
    /// Gets a value indicating whether this property is nullable.
    /// </summary>
    bool IsNullable { get; }

    /// <summary>
    /// Gets a value indicating whether this property is auto-generated (e.g., identity column).
    /// </summary>
    bool IsAutoGenerated { get; }

    /// <summary>
    /// Gets the maximum length for string properties.
    /// </summary>
    int? MaxLength { get; }
}
