using Ddap.Core;

namespace Ddap.Data;

/// <summary>
/// Concrete implementation of <see cref="IEntityConfiguration"/>.
/// </summary>
internal class EntityConfiguration : IEntityConfiguration
{
    /// <inheritdoc/>
    public required string EntityName { get; init; }

    /// <inheritdoc/>
    public string? SchemaName { get; init; }

    /// <inheritdoc/>
    public required IReadOnlyList<IPropertyConfiguration> Properties { get; init; }

    /// <inheritdoc/>
    public IReadOnlyList<IIndexConfiguration> Indexes { get; init; } =
        Array.Empty<IIndexConfiguration>();

    /// <inheritdoc/>
    public IReadOnlyList<IRelationshipConfiguration> Relationships { get; init; } =
        Array.Empty<IRelationshipConfiguration>();
}

/// <summary>
/// Concrete implementation of <see cref="IPropertyConfiguration"/>.
/// </summary>
internal class PropertyConfiguration : IPropertyConfiguration
{
    /// <inheritdoc/>
    public required string PropertyName { get; init; }

    /// <inheritdoc/>
    public required string ColumnName { get; init; }

    /// <inheritdoc/>
    public required Type PropertyType { get; init; }

    /// <inheritdoc/>
    public required string DatabaseType { get; init; }

    /// <inheritdoc/>
    public bool IsPrimaryKey { get; init; }

    /// <inheritdoc/>
    public bool IsNullable { get; init; }

    /// <inheritdoc/>
    public bool IsAutoGenerated { get; init; }

    /// <inheritdoc/>
    public int? MaxLength { get; init; }
}

/// <summary>
/// Concrete implementation of <see cref="IIndexConfiguration"/>.
/// </summary>
internal class IndexConfiguration : IIndexConfiguration
{
    /// <inheritdoc/>
    public required string IndexName { get; init; }

    /// <inheritdoc/>
    public required IReadOnlyList<string> PropertyNames { get; init; }

    /// <inheritdoc/>
    public bool IsUnique { get; init; }

    /// <inheritdoc/>
    public bool IsClustered { get; init; }
}

/// <summary>
/// Concrete implementation of <see cref="IRelationshipConfiguration"/>.
/// </summary>
internal class RelationshipConfiguration : IRelationshipConfiguration
{
    /// <inheritdoc/>
    public required string RelationshipName { get; init; }

    /// <inheritdoc/>
    public required string RelatedEntityName { get; init; }

    /// <inheritdoc/>
    public required RelationshipType RelationshipType { get; init; }

    /// <inheritdoc/>
    public required IReadOnlyList<string> ForeignKeyProperties { get; init; }

    /// <inheritdoc/>
    public required IReadOnlyList<string> PrincipalKeyProperties { get; init; }

    /// <inheritdoc/>
    public bool IsRequired { get; init; }
}
