using Ddap.Core;
using Ddap.Rest.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Ddap.Rest;

/// <summary>
/// Base controller for dynamically generated entity endpoints.
/// This class is partial to allow for extensibility.
/// Supports content negotiation - responses can be in JSON (default), XML, or YAML format
/// based on the Accept header in the request.
/// </summary>
/// <example>
/// To extend this controller, create a partial class:
/// <code>
/// public partial class EntityController
/// {
///     // Add custom methods here
/// }
/// </code>
/// 
/// To request different formats:
/// <code>
/// // JSON (default with Newtonsoft.Json)
/// GET /api/entity
/// Accept: application/json
/// 
/// // XML
/// GET /api/entity
/// Accept: application/xml
/// 
/// // YAML
/// GET /api/entity
/// Accept: application/yaml
/// </code>
/// </example>
[ApiController]
[Route("api/[controller]")]
[Produces("application/json", "application/xml", "application/yaml")]
public partial class EntityController : ControllerBase
{
    private readonly IEntityRepository _entityRepository;

    /// <summary>
    /// Initializes a new instance of the <see cref="EntityController"/> class.
    /// </summary>
    /// <param name="entityRepository">The entity repository.</param>
    public EntityController(IEntityRepository entityRepository)
    {
        _entityRepository = entityRepository;
    }

    /// <summary>
    /// Gets all available entities with optional filtering, sorting, and pagination.
    /// </summary>
    /// <param name="parameters">Query parameters for filtering, sorting, and pagination.</param>
    /// <returns>A paginated list of entity names.</returns>
    /// <response code="200">Returns the paginated list of available entities</response>
    /// <example>
    /// <code>
    /// // GET /api/entity?pageNumber=1&amp;pageSize=10&amp;orderBy=entityName asc
    /// </code>
    /// </example>
    [HttpGet]
    [ProducesResponseType(StatusCodes.Status200OK)]
    public IActionResult GetAllEntities([FromQuery] QueryParameters parameters)
    {
        var entities = _entityRepository.GetAllEntities();
        var entityData = entities.Select(e => new
        {
            e.EntityName,
            e.SchemaName,
            PropertyCount = e.Properties.Count
        }).ToList();

        var totalCount = entityData.Count;
        
        // Apply pagination
        var pagedItems = entityData
            .Skip((parameters.PageNumber - 1) * parameters.PageSize)
            .Take(parameters.PageSize);

        var result = new PagedResult<object>(pagedItems, totalCount, parameters.PageNumber, parameters.PageSize);
        return Ok(result);
    }

    /// <summary>
    /// Gets metadata for a specific entity.
    /// </summary>
    /// <param name="entityName">The name of the entity.</param>
    /// <returns>The entity metadata.</returns>
    /// <response code="200">Returns the entity metadata</response>
    /// <response code="404">If the entity is not found</response>
    [HttpGet("{entityName}/metadata")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public IActionResult GetEntityMetadata(string entityName)
    {
        var entity = _entityRepository.GetEntity(entityName);

        if (entity == null)
        {
            return NotFound(new { message = $"Entity '{entityName}' not found" });
        }

        return Ok(new
        {
            entity.EntityName,
            entity.SchemaName,
            Properties = entity.Properties.Select(p => new
            {
                p.PropertyName,
                p.ColumnName,
                PropertyType = p.PropertyType.Name,
                p.DatabaseType,
                p.IsPrimaryKey,
                p.IsNullable,
                p.IsAutoGenerated,
                p.MaxLength
            }),
            Indexes = entity.Indexes.Select(i => new
            {
                i.IndexName,
                i.PropertyNames,
                i.IsUnique,
                i.IsClustered
            }),
            Relationships = entity.Relationships.Select(r => new
            {
                r.RelationshipName,
                r.RelatedEntityName,
                RelationshipType = r.RelationshipType.ToString(),
                r.ForeignKeyProperties,
                r.PrincipalKeyProperties,
                r.IsRequired
            })
        });
    }
}
