using Ddap.Core;
using Microsoft.AspNetCore.Mvc;

namespace Ddap.Rest;

/// <summary>
/// Base controller for dynamically generated entity endpoints.
/// This class is partial to allow for extensibility.
/// </summary>
/// <example>
/// To extend this controller, create a partial class:
/// <code>
/// public partial class EntityController
/// {
///     // Add custom methods here
/// }
/// </code>
/// </example>
[ApiController]
[Route("api/[controller]")]
public partial class EntityController : ControllerBase
{
    private readonly IEntityRepository _entityRepository;

    /// <summary>
    /// Initializes a new instance of the <see cref="EntityController"/> class.
    /// </summary>
    /// <param name="entityRepository">The entity repository.</param>
    public EntityController(IEntityRepository entityRepository)
    {
        _entityRepository = entityRepository;
    }

    /// <summary>
    /// Gets all available entities.
    /// </summary>
    /// <returns>A list of entity names.</returns>
    /// <response code="200">Returns the list of available entities</response>
    [HttpGet]
    [ProducesResponseType(StatusCodes.Status200OK)]
    public IActionResult GetAllEntities()
    {
        var entities = _entityRepository.GetAllEntities();
        var entityNames = entities.Select(e => new
        {
            e.EntityName,
            e.SchemaName,
            PropertyCount = e.Properties.Count
        });

        return Ok(entityNames);
    }

    /// <summary>
    /// Gets metadata for a specific entity.
    /// </summary>
    /// <param name="entityName">The name of the entity.</param>
    /// <returns>The entity metadata.</returns>
    /// <response code="200">Returns the entity metadata</response>
    /// <response code="404">If the entity is not found</response>
    [HttpGet("{entityName}/metadata")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public IActionResult GetEntityMetadata(string entityName)
    {
        var entity = _entityRepository.GetEntity(entityName);

        if (entity == null)
        {
            return NotFound(new { message = $"Entity '{entityName}' not found" });
        }

        return Ok(new
        {
            entity.EntityName,
            entity.SchemaName,
            Properties = entity.Properties.Select(p => new
            {
                p.PropertyName,
                p.ColumnName,
                PropertyType = p.PropertyType.Name,
                p.DatabaseType,
                p.IsPrimaryKey,
                p.IsNullable,
                p.IsAutoGenerated,
                p.MaxLength
            }),
            Indexes = entity.Indexes.Select(i => new
            {
                i.IndexName,
                i.PropertyNames,
                i.IsUnique,
                i.IsClustered
            }),
            Relationships = entity.Relationships.Select(r => new
            {
                r.RelationshipName,
                r.RelatedEntityName,
                RelationshipType = r.RelationshipType.ToString(),
                r.ForeignKeyProperties,
                r.PrincipalKeyProperties,
                r.IsRequired
            })
        });
    }
}
