using Ddap.Core;
using Ddap.Core.Internals;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Ddap.Data.EntityFramework;

/// <summary>
/// Data provider implementation for Entity Framework Core.
/// Works with any EF Core provider (SQL Server, MySQL, PostgreSQL, SQLite, etc.).
/// </summary>
/// <typeparam name="TContext">The DbContext type.</typeparam>
public class EntityFrameworkDataProvider<TContext> : IDataProvider
    where TContext : DbContext
{
    private readonly IDbContextFactory<TContext> _contextFactory;
    private readonly EntityFrameworkProviderOptions _providerOptions;
    private readonly DdapOptions _options;

    /// <summary>
    /// Initializes a new instance of the <see cref="EntityFrameworkDataProvider{TContext}"/> class.
    /// </summary>
    /// <param name="contextFactory">The DbContext factory.</param>
    /// <param name="providerOptions">The EntityFramework provider options.</param>
    /// <param name="options">The DDAP configuration options.</param>
    public EntityFrameworkDataProvider(
        IDbContextFactory<TContext> contextFactory,
        EntityFrameworkProviderOptions providerOptions,
        DdapOptions options
    )
    {
        _contextFactory = contextFactory;
        _providerOptions = providerOptions;
        _options = options;
    }

    /// <inheritdoc/>
    public string ProviderName => "EntityFramework";

    /// <inheritdoc/>
    public async Task<IReadOnlyList<IEntityConfiguration>> LoadEntitiesAsync(
        CancellationToken cancellationToken = default
    )
    {
        await using var context = await _contextFactory.CreateDbContextAsync(cancellationToken);

        var model = context.Model;
        var entities = new List<IEntityConfiguration>();

        foreach (var entityType in model.GetEntityTypes())
        {
            // Skip if not mapped to a table
            var tableName = entityType.GetTableName();
            if (string.IsNullOrEmpty(tableName))
                continue;

            // Apply entity filter if provided
            if (
                _providerOptions.EntityFilter != null
                && !_providerOptions.EntityFilter(entityType.ClrType)
            )
                continue;

            // Apply global entity filter if provided
            if (_options.EntityFilter != null && !_options.EntityFilter(entityType.ClrType))
                continue;

            // Apply table filters
            if (_options.IncludeTables?.Count > 0 && !_options.IncludeTables.Contains(tableName))
                continue;

            if (_options.ExcludeTables?.Contains(tableName) == true)
                continue;

            if (_options.TableFilter != null && !_options.TableFilter(tableName))
                continue;

            var schemaName = entityType.GetSchema() ?? "dbo";

            // Apply schema filters
            if (_options.IncludeSchemas?.Count > 0 && !_options.IncludeSchemas.Contains(schemaName))
                continue;

            if (_options.ExcludeSchemas?.Contains(schemaName) == true)
                continue;

            var properties = LoadProperties(entityType);
            var indexes = LoadIndexes(entityType);
            var relationships = LoadRelationships(entityType);

            entities.Add(
                new EntityConfiguration
                {
                    EntityName = entityType.ClrType.Name,
                    SchemaName = schemaName,
                    Properties = properties,
                    Indexes = indexes,
                    Relationships = relationships,
                }
            );
        }

        return entities;
    }

    private IReadOnlyList<IPropertyConfiguration> LoadProperties(IEntityType entityType)
    {
        var properties = new List<IPropertyConfiguration>();

        foreach (var property in entityType.GetProperties())
        {
            var primaryKey = entityType.FindPrimaryKey();
            var isPrimaryKey = primaryKey?.Properties.Contains(property) == true;

            properties.Add(
                new PropertyConfiguration
                {
                    PropertyName = property.Name,
                    ColumnName = property.GetColumnName() ?? property.Name,
                    PropertyType = property.ClrType,
                    DatabaseType = property.GetColumnType(),
                    IsPrimaryKey = isPrimaryKey,
                    IsNullable = property.IsNullable,
                    IsAutoGenerated = property.ValueGenerated != ValueGenerated.Never,
                    MaxLength = property.GetMaxLength(),
                }
            );
        }

        return properties;
    }

    private IReadOnlyList<IIndexConfiguration> LoadIndexes(IEntityType entityType)
    {
        var indexes = new List<IIndexConfiguration>();

        foreach (var index in entityType.GetIndexes())
        {
            indexes.Add(
                new IndexConfiguration
                {
                    IndexName =
                        index.Name
                        ?? $"IX_{string.Join("_", index.Properties.Select(p => p.Name))}",
                    PropertyNames = index.Properties.Select(p => p.Name).ToList(),
                    IsUnique = index.IsUnique,
                    IsClustered = false, // EF Core doesn't expose this directly
                }
            );
        }

        return indexes;
    }

    private IReadOnlyList<IRelationshipConfiguration> LoadRelationships(IEntityType entityType)
    {
        var relationships = new List<IRelationshipConfiguration>();

        foreach (var navigation in entityType.GetNavigations())
        {
            var foreignKey = navigation.ForeignKey;

            // Determine relationship type based on navigation properties
            RelationshipType relationshipType;
            if (navigation.IsCollection)
            {
                relationshipType = RelationshipType.OneToMany;
            }
            else if (foreignKey.IsUnique)
            {
                relationshipType = RelationshipType.OneToOne;
            }
            else
            {
                relationshipType = RelationshipType.OneToMany; // Default to OneToMany
            }

            relationships.Add(
                new RelationshipConfiguration
                {
                    RelationshipName = navigation.Name,
                    RelatedEntityName = navigation.TargetEntityType.ClrType.Name,
                    RelationshipType = relationshipType,
                    ForeignKeyProperties = foreignKey.Properties.Select(p => p.Name).ToList(),
                    PrincipalKeyProperties = foreignKey
                        .PrincipalKey.Properties.Select(p => p.Name)
                        .ToList(),
                    IsRequired = !foreignKey.IsRequired,
                }
            );
        }

        return relationships;
    }
}
