using Ddap.Core;

namespace Ddap.Core.Internals;

/// <summary>
/// Concrete implementation of <see cref="IPropertyConfiguration"/>.
/// </summary>
internal class PropertyConfiguration : IPropertyConfiguration
{
    /// <inheritdoc/>
    public required string PropertyName { get; init; }

    /// <inheritdoc/>
    public required string ColumnName { get; init; }

    /// <inheritdoc/>
    public required Type PropertyType { get; init; }

    /// <inheritdoc/>
    public required string DatabaseType { get; init; }

    /// <inheritdoc/>
    public bool IsPrimaryKey { get; init; }

    /// <inheritdoc/>
    public bool IsNullable { get; init; }

    /// <inheritdoc/>
    public bool IsAutoGenerated { get; init; }

    /// <inheritdoc/>
    public int? MaxLength { get; init; }
}
